name: create tflite

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: create tflite
      run: |
        python3 whisper2tflite.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: whisper2tflite.py
        path: whisper2tflite.py