name: create tflite

on:
  push:
    tags:
      - "build-*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build-steps.yml
# i do not want to mess with atomatically created releases
#  release:
#    runs-on: ubuntu-latest
#    needs: build
#    if: startsWith(github.ref, 'refs/tags/v')
#    steps:
#      - name: Extract tag name
#        id: extract_tag_name
#        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
#
#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.TAG_NAME }}
#          release_name: Release ${{ env.TAG_NAME }}
#          draft: false
#          prerelease: false