name: create tflite

on:
  release:
    types:
      - published

jobs:
  build:
    uses: ./.github/workflows/build-steps.yml

  package:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: whisper.tflite

    - name: zip
      run: |
        zip whisper.tflite-${{ github.event.release.tag_name }}.zip whisper.tflite

    - name: Upload release package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./whisper.tflite-${{ github.event.release.tag_name }}.zip
        asset_name: whisper.tflite-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
